export const categories = [
    "Teas",
    "Luxury Hot Chocolate",
    "Milkshakes",
];

export const allItems = [
    {
        title: "English Breakfast Tea",
        price: "£3.95",
        desc: "Traditional black tea blend.",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Traditional Chai Tea",
        price: "£3.95",
        desc: "Rich and warming spiced chai.",
        category: "Teas",
        image: "/Chicken.png",
    },
    {
        title: "Spiced Apple Tea",
        price: "£3.95",
        desc: "Sweet apple with warming spices.",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Earl Grey",
        price: "£3.95",
        desc: "Classic bergamot-infused black tea.",
        category: "Teas",
        image: "/Chicken.png",
    },
    {
        title: "Truffle & Coffee Tea",
        price: "£3.95",
        desc: "A unique blend with rich coffee notes.",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Immuni-Tea",
        price: "£3.95",
        desc: "A refreshing blend designed to invigorate.",
        category: "Teas",
        image: "/Chicken.png",
    },
    {
        title: "Rose Coconut Green Tea",
        price: "£3.95",
        desc: "Delicate green tea with rose and coconut.",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Parisian Drinking Chocolate",
        price: "£4.00",
        desc: "Small serving of thick, strong European-style drinking chocolate.",
        category: "Luxury Hot Chocolate",
        image: "/Chicken.png",
    },
    {
        title: "Luxury Hot Chocolate",
        price: "£4.95",
        desc: "Topped with cream and marshmallows.",
        category: "Luxury Hot Chocolate",
        image: "/g6.jpg",
    },
    {
        title: "Chocolate Orange",
        price: "£4.50",
        desc: "Rich chocolate with a zesty orange twist.",
        category: "Luxury Hot Chocolate",
        image: "/Chicken.png",
    },
    {
        title: "Mint Chocolate",
        price: "£4.50",
        desc: "Smooth chocolate with a refreshing mint flavour.",
        category: "Luxury Hot Chocolate",
        image: "/g6.jpg",
    },
    {
        title: "Hazelnut Chocolate",
        price: "£4.50",
        desc: "Creamy chocolate with roasted hazelnut flavour.",
        category: "Luxury Hot Chocolate",
        image: "/Chicken.png",
    },
    {
        title: "Caramel Hot Chocolate",
        price: "£4.50",
        desc: "Rich chocolate blended with sweet caramel.",
        category: "Luxury Hot Chocolate",
        image: "/g6.jpg",
    },
    {
        title: "Banoffee",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Maltesers",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Oreo's",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Peanut Butter and Jam",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Strawberry Shortcake",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Mint Chocolate",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Chocolate Orange",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Nutella",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Daim Bar",
        price: "£5.50",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
];
