export const categories = [
    "Hot & Cold Sandwiches",
    "Street Food",
    "Mishti Milkshakes",
    "Cold Drinks",
    "Ice Coffee",
    "100% Fresh Juice",
    "Tea & Coffee",
];

export const allItems = [
    //Hot & Cold Sandwiches
    {
        title: "Cheese Salad Baguette",
        price: "£3.50",
        desc: "",
        category: "Hot & Cold Sandwiches",
        image: "/g6.jpg",
    },
    {
        title: "Chicken Baguette",
        price: "£3.50",
        desc: "Freshly baked baguette with seasoned chicken, red onions, cucumber, and mayo. Available hot or cold.",
        category: "Hot & Cold Sandwiches",
        image: "/Chicken.png",
    },
    {
        title: "Tuna Baguette",
        price: "£3.50",
        desc: "Fresh baguette with seasoned tuna, mayo, onions, mustard, and crisp cucumber for a savory delight.",
        category: "Hot & Cold Sandwiches",
        image: "/Tuna Baguette.png",
    },
    {
        title: "Tuna Cob",
        price: "£2.00",
        desc: "Tuna-filled sub with fresh veggies and a hint of seasoning, perfect for a quick and satisfying meal.",
        category: "Hot & Cold Sandwiches",
        image: "/Tuna cob.png",
    },
    {
        title: "Chicken Cob",
        price: "£2.00",
        desc: `Tender chicken in a 6" sub, layered with fresh ingredients for a satisfying bite.`,
        category: "Hot & Cold Sandwiches",
        image: "/Chicken cob.png",
    },
    {
        title: "Chilli Cheese Toastie",
        price: "£2.50",
        desc: "mixed cheese with red & green bell peppers ,mild green chillies served toasted",
        category: "Hot & Cold Sandwiches",
        image: "/g18.jpg",
    },
    {
        title: "Pepperoni & Cheese Toasty",
        price: "£3.50",
        desc: "Our famous toastie with pepperoni and chili, offering a spicy twist on a classic cheese delight.",
        category: "Hot & Cold Sandwiches",
        image: "/Pepperoni and Cheese.png",
    },
    {
        title: " Pepperoni & Cheese Bagel",
        price: "£3.00",
        desc: "Beef Pepperoni with Cheddar Cheese Toasted",
        category: "Hot & Cold Sandwiches",
        image: "/Pepperoni.png",
    },
    {
        title: "Double Cheese Bagel",
        price: "£2.00",
        desc: "",
        category: "Hot & Cold Sandwiches",
        image: "/Double Cheese Bagel.png",
    },
    {
        title: "Cheese & Tomato Bagel",
        price: "£2.25",
        desc: "Freshly baked bagel filled with melted cheese and juicy tomato.",
        category: "Hot & Cold Sandwiches",
        image: "/g12.webp",
    },
    {
        title: "Sausage and Hash brown Baguette",
        price: "£3.50",
        desc: "",
        category: "Hot & Cold Sandwiches",
        image: "/Sausage.png",
    },
    {
        title: "Salmon Bagel",
        price: "£3.50",
        desc: "",
        category: "Hot & Cold Sandwiches",
        image: "/Salmon.png",
    },

    //Street Food
    {
        title: "Samosas (Mixed Veg)",
        price: "£1.00",
        desc: "Mixed veg samosa with a blend of spices, offering a delightful street food experience. Made Fresh Daily, limited availability",
        category: "Street Food",
        image: "/Samosas.png",
    },
    {
        title: "Samosas (Chicken)",
        price: "£1.50",
        desc: "Freshly made chicken samosas, limited availability. Best in town for a savory street food experience.",
        category: "Street Food",
        image: "/Samosas.png",
    },
    {
        title: "Samosa Chatt",
        price: "£5.00",
        desc: "2 samosas (either mixed veg or potato subject to availability) , with a spicy Papri chatt topped pomegranate",
        category: "Street Food",
        image: "/g3.jpg",
    },
    {
        title: "Spicy chana chatt",
        price: "£3.50",
        desc: "Zesty chickpeas tossed in homemade spicy sauces, offering a burst of Indian street food flavors.",
        category: "Street Food",
        image: "/spicy channa chaat.png",
    },
    {
        title: "Chicken Kebab Bap",
        price: "£4.00",
        desc: "",
        category: "Street Food",
        image: "/Chicken Kebab Bap.png",
    },
    {
        title: "Chicken & Spinach Pasty",
        price: "£3.50",
        desc: "Handmade pasty filled with chicken and spinach, wrapped in flaky pastry for a savory street food delight.",
        category: "Street Food",
        image: "/Chicken & Spinach Pasty.png",
    },
    {
        title: "Hashbrown Cob",
        price: "£1.50",
        desc: "Crispy shredded potatoes in a delicious cob shape.",
        category: "Street Food",
        image: "/hashbrown.png",
    },
    {
        title: "Masala Omelette Parata",
        price: "£3.00",
        desc: "Spiced masala omelette wrapped in a soft paratha for a flavorful street food delight.",
        category: "Street Food",
        image: "/masala.png",
    },
    {
        title: "Butter Parata",
        price: "£1.20",
        desc: "",
        category: "Street Food",
        image: "/Butter Parata.png",
    },
    {
        title: "Masala Omelette",
        price: "£2.00",
        desc: "",
        category: "Street Food",
        image: "/masala.png",
    },
    {
        title: "Double Omelette Parata",
        price: "£4.00",
        desc: "",
        category: "Street Food",
        image: "/Double Omelette Parata.png",
    },
    {
        title: "Desi Breakfast",
        price: "£7.50",
        desc: "",
        category: "Street Food",
        image: "/masala.png",
    },
    {
        title: "FullyLoaded Breakfast Wrap",
        price: "£4.50",
        desc: "Paratha, Masala Omelette with hashbrown, Beef or Turkey pepperoni, Beef or Turkey rashers, jalepenos , cheese, masala chilli sauce.",
        category: "Street Food",
        image: "/FullyLoaded Breakfast Wrap.png",
    },
    {
        title: "Sheesh Kebab Parata Roll",
        price: "£3.00",
        desc: "",
        category: "Street Food",
        image: "/Sheesh Kebab Parata Roll.png",
    },
    {
        title: "Sheesh Kebab Egg Roll",
        price: "£4.50",
        desc: "Rolled egg and kebab delight, perfect for street food lovers seeking a quick, satisfying bite.",
        category: "Street Food",
        image: "/Sheesh Kebab Egg Roll.jpeg",
    },
    {
        title: "Double Sheesh Kebab Pita",
        price: "£6.00",
        desc: "Lamb shish kebabs in pita with fresh salad for a delightful, savory meal.",
        category: "Street Food",
        image: "/Double Sheesh Kebab Pita.png",
    },
    {
        title: "Fruit 'n'nut Granola Bowl",
        price: "£3.49",
        desc: "made with coconut yoghurt, includes almonds, chia seeds, pumpkin seeds, cashew nuts, goji berries and fruit'n'nut Granola",
        category: "Street Food",
        image: "/Fruit n nut.png",
    },
    {
        title: "Choc'n'nut Granola Bowl",
        price: "£2.00",
        desc: "made with coconut yoghurt, includes brazil nuts, almonds , cashew nuts , walnuts , chia seeds, chocolate chip granola",
        category: "Street Food",
        image: "/choc.png",
    },
    {
        title: "Masala Wedges",
        price: "£2.50",
        desc: "",
        category: "Street Food",
        image: "/Masala Wedges.png",
    },
    {
        title: "Butter Croissant",
        price: "£1.50",
        desc: "Flaky, buttery pastry.",
        category: "Street Food",
        image: "/croissant.png",
    },
    {
        title: "Almond/Choc Croissant",
        price: "£2.50",
        desc: "Flaky pastry filled with almond goodness.",
        category: "Street Food",
        image: "/AlmondChoc Croissant.png",
    },
    {
        title: "Chocolate Croissant",
        price: "£2.00",
        desc: "Flaky pastry filled with rich, velvety chocolate.",
        category: "Street Food",
        image: "/Chocolate.png",
    },
    {
        title: "White Chocolate Cookie",
        price: "£2.00",
        desc: "",
        category: "Street Food",
        image: "/White.png",
    },
    {
        title: "Chocolate Chip Cookie",
        price: "£2.00",
        desc: "",
        category: "Street Food",
        image: "/Chocolate2.png",
    },
    {
        title: "Double Chocolate Cookie",
        price: "£2.00",
        desc: "",
        category: "Street Food",
        image: "/Double Chocolate.png",
    },

    //Mishti Milkshakes
    {
        title: "Gulap Jam Milkshake",
        price: "£3.50",
        desc: "Chilled milkshake with gulab jamun, a house special for a sweet, creamy experience.",
        category: "Mishti Milkshakes",
        image: "/Gulap Jam Milkshake.png",
    },
    {
        title: "Kala Jam Milkshake",
        price: "£3.50",
        desc: "Indulge in a creamy milkshake blended with the unique flavor of kala jam.",
        category: "Mishti Milkshakes",
        image: "/Kala Jam Milkshake.png",
    },
    {
        title: "House Special",
        price: "£4.00",
        desc: "Indulge in a creamy milkshake with pistachio and salted caramel, featuring delightful mishti flavors.",
        category: "Mishti Milkshakes",
        image: "/House Special1.png",
    },

    //Cold Drink
    {
        title: "Mango Lassi",
        price: "£3.50",
        desc: "Refreshing blend of mango and yogurt, a perfect chilled treat for a sunny day.",
        category: "Cold Drinks",
        image: "/g13.png",
    },
    {
        title: "Brazilian Lemonade",
        price: "£3.95",
        desc: "Refreshing Brazilian lemonade with lime and ice, offering a sour twist to quench your thirst.",
        category: "Cold Drinks",
        image: "/g4.jpg",
    },
    {
        title: "Strawberry Lemonade",
        price: "£3.95",
        desc: "Sweet and sour strawberry lemonade, a refreshing summer drink perfect for cooling down.",
        category: "Cold Drinks",
        image: "/g8.jpg",
    },
    {
        title: "Mango & Passionfruit Twist",
        price: "£3.95",
        desc: "House Special",
        category: "Cold Drinks",
        image: "/Mango & Passionfruit Twist.png",
    },

    //Ice Coffee
    {
        title: "House Ice Coffee",
        price: "£3.95",
        desc: "Chilled house special ice coffee, customizable with vegan alternative milk for a refreshing experience.",
        category: "Ice Coffee",
        image: "/g2.jpg",
    },
    {
        title: "Caramel Ice Coffee",
        price: "£3.95",
        desc: "vegan alternative milk available",
        category: "Ice Coffee",
        image: "/Caramel Ice Coffee.png",
    },
    {
        title: "Vanilla Ice Coffee",
        price: "£3.95",
        desc: "vegan alternative milk available",
        category: "Ice Coffee",
        image: "/Vanilla Ice Coffee.png",
    },
    {
        title: "House Ice Mocha",
        price: "£3.95",
        desc: "Chilled blend of coffee, milk, and chocolate syrup over ice for a refreshing treat. vegan alternative milk available",
        category: "Ice Coffee",
        image: "/House Ice Mocha.png",
    },
    {
        title: "Ice Matcha Latte",
        price: "£3.95",
        desc: "",
        category: "Ice Coffee",
        image: "/Ice Matcha Latte.png",
    },

    //100% Fresh Juice"
    {
        title: "Orange Juice",
        price: "£3.50",
        desc: "Freshly pressed orange juice, bursting with natural sweetness and vibrant citrus flavor.",
        category: "100% Fresh Juice",
        image: "/Orange Juice.png",
    },
    {
        title: "Fresh Juice",
        price: "£5.00",
        desc: "",
        category: "100% Fresh Juice",
        image: "/g8.jpg",
    },
    {
        title: "Orange Juice + Ginger Shot",
        price: "£4.50",
        desc: "",
        category: "100% Fresh Juice",
        image: "/Orange Juice + Ginger Shot.png",
    },
    {
        title: "Ginger Shot",
        price: "£1.35",
        desc: "",
        category: "100% Fresh Juice",
        image: "/Ginger Shot.png",
    },
    {
        title: "Add Fresh Lime",
        price: "£0.65",
        desc: "",
        category: "100% Fresh Juice",
        image: "/Lime.png",
    },

    //Tea & Coffee
    {
        title: "Karak Chai",
        price: "£2.00",
        desc: "House Special",
        category: "Tea & Coffee",
        image: "/Karak Chai.png",
    },
    {
        title: "Masala Chai",
        price: "£2.20",
        desc: "",
        category: "Tea & Coffee",
        image: "/Masala Chai.png",
    },
    {
        title: "Pink Chai",
        price: "£2.20",
        desc: "Creamy, aromatic milk tea with a delicate pink colour.",
        category: "Tea & Coffee",
        image: "/Pink Chai.jpeg",
    },
    {
        title: "Caramel Chai",
        price: "£2.20",
        desc: "Sweet and spicy black tea infused with caramel flavour.",
        category: "Tea & Coffee",
        image: "/last.png",
    },
    {
        title: "Moroccan Tea",
        price: "£2.75",
        desc: "Traditional Moroccan brew, sweet and soothing.",
        category: "Tea & Coffee",
        image: "/Moroccan Tea.png",
    },
    {
        title: "English Tea",
        price: "£1.75",
        desc: "Strong and refreshing black tea, perfect for any time of day.",
        category: "Tea & Coffee",
        image: "/english.jpeg",
    },
    {
        title: "Mango Flower Tea",
        price: "£4.19",
        desc: "Floral and refreshing tea infused with mango flavour.",
        category: "Tea & Coffee",
        image: "/Mango Flower tea.png",
    },
    {
        title: "Karak Coffee",
        price: "£2.00",
        desc: "House Special",
        category: "Tea & Coffee",
        image: "/karak Coffee.png",
    },
    {
        title: "Chai Latte",
        price: "£2.20",
        desc: "contains caffeine , brewed fresh daily",
        category: "Tea & Coffee",
        image: "/Chai Latte.jpeg",
    },
    {
        title: "Espresso",
        price: "£1.50",
        desc: "Strong and rich coffee shot.",
        category: "Tea & Coffee",
        image: "/Espresso.png",
    },
    {
        title: "Americano",
        price: "£2.85",
        desc: "Espresso topped with hot water for a smooth, long black coffee.",
        category: "Tea & Coffee",
        image: "/Americano.png",
    },
    {
        title: "Cappuccino",
        price: "£2.85",
        desc: "Rich and smooth coffee drink with a velvety texture.",
        category: "Tea & Coffee",
        image: "/Cappuccino.png",
    },
    {
        title: "Hot Chocolate",
        price: "£2.00",
        desc: "Rich and creamy drink to warm your day.",
        category: "Tea & Coffee",
        image: "/Hot Chocolate.png",
    },
    {
        title: "Double Choc House Mocha",
        price: "£2.40",
        desc: "Rich and smooth coffee drink with a mocha flavour.",
        category: "Tea & Coffee",
        image: "/Double Choc House Mocha.png",
    },
];