export const categories = [
    "Teas",
    "Hot Chocolate",
    "Milkshakes",
];

export const allItems = [
    {
        title: "English breakfast tea",
        price: "",
        desc: "",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Traditional chai tea",
        price: "",
        desc: "",
        category: "Teas",
        image: "/Chicken.png",
    },
    {
        title: "Spiced apple tea",
        price: "",
        desc: "",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Earl grey",
        price: "",
        desc: "",
        category: "Teas",
        image: "/Chicken.png",
    },
    {
        title: "Truffle& coffee tea",
        price: "",
        desc: "",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Immuni-tea",
        price: "",
        desc: "",
        category: "Teas",
        image: "/Chicken.png",
    },
    {
        title: "Rose coconut green tea",
        price: "",
        desc: "",
        category: "Teas",
        image: "/g6.jpg",
    },
    {
        title: "Parisian Drinking chocolate (small cup thick strong )",
        price: "",
        desc: "",
        category: "Hot Chocolate",
        image: "/Chicken.png",
    },
    {
        title: "Luxury hot chocolate",
        price: "",
        desc: "",
        category: "Hot Chocolate",
        image: "/g6.jpg",
    },
    {
        title: "Chocolate orange",
        price: "",
        desc: "",
        category: "Hot Chocolate",
        image: "/Chicken.png",
    },
    {
        title: "Mint chocolate",
        price: "",
        desc: "",
        category: "Hot Chocolate",
        image: "/g6.jpg",
    },
    {
        title: "Hazelnut chocolate",
        price: "",
        desc: "",
        category: "Hot Chocolate",
        image: "/Chicken.png",
    },
    {
        title: "Caramel hot chocolate",
        price: "",
        desc: "",
        category: "Hot Chocolate",
        image: "/g6.jpg",
    },
    {
        title: "Banoffee",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Maltesers",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Oreo's",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "peanut butter and jam",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Strawberry shortcake",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Mint chocolate",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Chocolate orange",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
    {
        title: "Nutella",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/g6.jpg",
    },
    {
        title: "Daim bar",
        price: "",
        desc: "",
        category: "Milkshakes",
        image: "/Chicken.png",
    },
];
